export const CHANGE_NAME = 'CHANGE_NAME';
export const APP_THEME = 'APP_THEME';
export const HOME_SEARCH_TEXT = 'HOME_SEARCH_TEXT';
export const HOME_SCREEN_GET_DATA = 'HOME_SCREEN_GET_DATA'
export const HOME_SCREEN_TOGGLE_LOADING = "HOME_SCREEN_TOGGLE_LOADING"
